// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionOrquesta.Models;

#nullable disable

namespace SistemaGestionOrquesta.Migrations
{
    [DbContext(typeof(OrquestaOESATContext))]
    [Migration("20240118011218_AgregarCamposTutorEstudiante")]
    partial class AgregarCamposTutorEstudiante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AlumnosCurso", b =>
                {
                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstudianteID");

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    b.HasKey("EstudianteId", "CursoId")
                        .HasName("PK__AlumnosC__F7468990458DE6AB");

                    b.HasIndex("CursoId");

                    b.ToTable("AlumnosCurso", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProfesorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfesorID");

                    b.HasKey("CursoId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Curso", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.Property<Guid>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstudianteID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Asegurado")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("InstrumentoId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentoID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Tutor");

                    b.Property<string>("NombreTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoTutor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono_Tutor");

                    b.Property<string>("TelefonoTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("Estudiante", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Instrumento", b =>
                {
                    b.Property<int>("InstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstrumentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentoId"), 1L, 1);

                    b.Property<string>("Detalles")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstrumentoId");

                    b.ToTable("Instrumento", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.PrestamoInstrumento", b =>
                {
                    b.Property<int>("PrestamoInstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoInstrumentoId"), 1L, 1);

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoInstrumentoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("PrestamosInstrumentos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Profesor", b =>
                {
                    b.Property<Guid>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfesorID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesor", (string)null);
                });

            modelBuilder.Entity("AlumnosCurso", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .IsRequired()
                        .HasConstraintName("FK__AlumnosCu__Curso__5535A963");

                    b.HasOne("SistemaGestionOrquesta.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .IsRequired()
                        .HasConstraintName("FK__AlumnosCu__Alumn__5441852A");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Curso", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Profesor", "Profesor")
                        .WithMany("Cursos")
                        .HasForeignKey("ProfesorId")
                        .HasConstraintName("FK__Curso__ProfesorI__4CA06362");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Instrumento", "Instrumento")
                        .WithMany("Estudiantes")
                        .HasForeignKey("InstrumentoId")
                        .HasConstraintName("FK__Alumnos__Instrum__5629CD9C");

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.PrestamoInstrumento", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Estudiante", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionOrquesta.Models.Instrumento", "Instrumento")
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Instrumento", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Profesor", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
