// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionOrquesta.Models;

#nullable disable

namespace SistemaGestionOrquesta.Migrations
{
    [DbContext(typeof(OrquestaOESATContext))]
    [Migration("20260412021229_AddEventosCalendarioYEstadoAsistencia")]
    partial class AddEventosCalendarioYEstadoAsistencia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AlumnosCurso", b =>
                {
                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstudianteID");

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    b.HasKey("EstudianteId", "CursoId")
                        .HasName("PK__AlumnosC__F7468990458DE6AB");

                    b.HasIndex(new[] { "CursoId" }, "IX_AlumnosCurso_CursoID");

                    b.ToTable("AlumnosCurso", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsistenciaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"), 1L, 1);

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    b.Property<string>("EstadoAsistencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstudianteID");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId", "CursoId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("IX_Asistencia_Estudiante_Curso_Fecha");

                    b.ToTable("Asistencia", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProfesorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfesorID");

                    b.HasKey("CursoId");

                    b.HasIndex(new[] { "ProfesorId" }, "IX_Curso_ProfesorID");

                    b.ToTable("Curso", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.Property<Guid>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EstudianteID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Asegurado")
                        .HasColumnType("bit");

                    b.Property<bool?>("Autoretiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EpPsicoMotriz")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ep_psico_motriz")
                        .HasDefaultValueSql("('sin observaciones')");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("InstrumentoId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentoID");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Tutor");

                    b.Property<string>("NombreTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Particularidad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("('sin observaciones')");

                    b.Property<string>("RutaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoTutor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono_Tutor");

                    b.Property<string>("TelefonoTutor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TmtMédico")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tmt_médico")
                        .HasDefaultValueSql("('sin observaciones')");

                    b.HasKey("EstudianteId");

                    b.HasIndex(new[] { "InstrumentoId" }, "IX_Estudiante_InstrumentoID");

                    b.ToTable("Estudiante", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Evento", b =>
                {
                    b.Property<string>("EventoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EventoID");

                    b.Property<string>("AttendeesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EventoId");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Instrumento", b =>
                {
                    b.Property<int>("InstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstrumentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentoId"), 1L, 1);

                    b.Property<string>("Detalles")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstrumentoId");

                    b.ToTable("Instrumento", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.PrestamosInstrumento", b =>
                {
                    b.Property<int>("PrestamoInstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoInstrumentoId"), 1L, 1);

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("int");

                    b.Property<int>("StockInstrumentoId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoInstrumentoId");

                    b.HasIndex(new[] { "EstudianteId" }, "IX_PrestamosInstrumentos_EstudianteId");

                    b.HasIndex(new[] { "InstrumentoId" }, "IX_PrestamosInstrumentos_InstrumentoId");

                    b.HasIndex(new[] { "StockInstrumentoId" }, "IX_PrestamosInstrumentos_StockInstrumentoId");

                    b.ToTable("PrestamosInstrumentos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Profesor", b =>
                {
                    b.Property<Guid>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfesorID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesor", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.StockInstrumento", b =>
                {
                    b.Property<int>("StockInstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockInstrumentoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockInstrumentoId"), 1L, 1);

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Disponible");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentoID");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StockInstrumentoId");

                    b.HasIndex("CodigoInventario")
                        .IsUnique();

                    b.HasIndex("InstrumentoId");

                    b.ToTable("StockInstrumento", (string)null);
                });

            modelBuilder.Entity("AlumnosCurso", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .IsRequired()
                        .HasConstraintName("FK__AlumnosCu__Curso__5535A963");

                    b.HasOne("SistemaGestionOrquesta.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .IsRequired()
                        .HasConstraintName("FK__AlumnosCu__Alumn__5441852A");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Asistencia", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionOrquesta.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Curso", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Profesor", "Profesor")
                        .WithMany("Cursos")
                        .HasForeignKey("ProfesorId")
                        .HasConstraintName("FK__Curso__ProfesorI__4CA06362");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Instrumento", "Instrumento")
                        .WithMany("Estudiantes")
                        .HasForeignKey("InstrumentoId")
                        .HasConstraintName("FK__Alumnos__Instrum__5629CD9C");

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.PrestamosInstrumento", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Estudiante", "Estudiante")
                        .WithMany("PrestamosInstrumentos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionOrquesta.Models.Instrumento", "Instrumento")
                        .WithMany("PrestamosInstrumentos")
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionOrquesta.Models.StockInstrumento", "StockInstrumento")
                        .WithMany("PrestamosInstrumentos")
                        .HasForeignKey("StockInstrumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Instrumento");

                    b.Navigation("StockInstrumento");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.StockInstrumento", b =>
                {
                    b.HasOne("SistemaGestionOrquesta.Models.Instrumento", "Instrumento")
                        .WithMany("StockInstrumentos")
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Estudiante", b =>
                {
                    b.Navigation("PrestamosInstrumentos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Instrumento", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("PrestamosInstrumentos");

                    b.Navigation("StockInstrumentos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.Profesor", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("SistemaGestionOrquesta.Models.StockInstrumento", b =>
                {
                    b.Navigation("PrestamosInstrumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
