name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.4' # Especificar la versión 8.0.4 de .NET

      - name: Restore dependencies
        run: dotnet restore BlazorAppOrquesta/BlazorAppOrquesta.csproj

      - name: Build
        run: dotnet build BlazorAppOrquesta/BlazorAppOrquesta.csproj --configuration Release

      - name: Publish
        run: dotnet publish BlazorAppOrquesta/BlazorAppOrquesta.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BEACH_0A3E3EC10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integraciones con Github (por ejemplo, comentarios en PR)
          action: "upload"
          ###### Configuraciones del repositorio/compilación - Estos valores pueden configurarse para que coincidan con los requisitos de tu aplicación. ######
          # Para más información sobre las configuraciones del flujo de trabajo de Static Web App, por favor visita: https://aka.ms/swaworkflowconfig
          app_location: "BlazorAppOrquesta" # Ruta del código fuente de la aplicación
          api_location: "Api" # Ruta del código fuente de la API - opcional
          output_location: "BlazorAppOrquesta/wwwroot" # Directorio del contenido compilado de la aplicación - opcional
          ###### Fin de las configuraciones del repositorio/compilación ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BEACH_0A3E3EC10 }}
          action: "close"
